# Generated by Django 5.0.3 on 2024-04-15 18:13

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutHistory',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstpara', models.CharField(max_length=1000)),
                ('secondpara', models.CharField(max_length=2000)),
                ('thirdpara', models.CharField(max_length=1000)),
                ('fourthpara', models.CharField(max_length=1000)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPrinciple',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('principleintro', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='principleimg/')),
                ('firstpara', models.CharField(max_length=1000)),
                ('secondpara', models.CharField(max_length=2000)),
                ('thirdpara', models.CharField(max_length=1000)),
                ('fourthpara', models.CharField(max_length=1000)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutVision',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstpara', models.CharField(max_length=1000)),
                ('secondpara', models.CharField(max_length=2000)),
                ('thirdpara', models.CharField(max_length=1000)),
                ('fourthpara', models.CharField(max_length=1000)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_experiences', models.IntegerField(unique=True)),
                ('teacher_no', models.IntegerField()),
                ('bright_students', models.IntegerField(unique=True)),
                ('glorious_alumini', models.IntegerField(unique=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='profile/')),
                ('gmail', models.EmailField(max_length=200)),
                ('phn_no', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.URLField(max_length=1000)),
                ('gmail_api', models.URLField(max_length=300)),
                ('gmail', models.EmailField(max_length=300)),
                ('phn_no', models.CharField(max_length=10)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallery/')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSwiper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('position', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='swiper/')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstpara', models.CharField(max_length=1000)),
                ('secondpara', models.CharField(max_length=2000)),
                ('thirdpara', models.CharField(max_length=1000)),
                ('fourthpara', models.CharField(max_length=1000)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='profile/')),
                ('gmail', models.EmailField(max_length=200)),
                ('phn_no', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoreDoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='moredocument/')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=300)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('file1', models.FileField(upload_to='Notice/img')),
                ('title2', models.CharField(default=None, max_length=200)),
                ('file2', models.FileField(default=None, upload_to='Notice/')),
                ('title3', models.CharField(default=None, max_length=200)),
                ('file3', models.FileField(default=None, upload_to='Notice/')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facebook', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('linkedin', models.URLField(max_length=300)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
