# Generated by Django 5.0.3 on 2024-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminap', '0002_alter_admin_user_alter_moderator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
