# Generated by Django 5.0.3 on 2024-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminap', '0003_alter_costumuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='gmail',
        ),
        migrations.AddField(
            model_name='admin',
            name='post',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderator',
            name='post',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
